version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: book_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: book_database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Admin
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_CONTAINER_NAME: postgres_db
    depends_on:
      - db

volumes:
  postgres_data:
